# Generated by Django 3.2.4 on 2021-06-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50, verbose_name='Название')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('item_new', models.BooleanField(verbose_name='Новинка')),
            ],
        ),
    ]
