# Generated by Django 3.2.4 on 2021-07-11 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flux_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cards',
            options={'ordering': ['item_new', 'price']},
        ),
    ]
